### ISSUE TITLE
Unable to Open resource

### ISSUE THREAD

**Issue by konsolu** [BuXXe/movian-bs-plugin#3]
Whenever I try to browse or search I get following error:

Unable to Open resource
bs.to::Browse
Cannot read property 'getElementByTagName' of Null

I am using the PS3 and Android Version of Movian

**Comment by BuXXe** [comment]
Thanks for the message. I need to rework many parts of my plugins and I will have a look at it as soon as I can

**Comment by BuXXe** [comment]
Solved the problem with 7df267096d855297624cae8079813c07bb18bda1
