### ISSUE TITLE
bs.to isnt working. I get this issue "cannot read property 'attributes' of undefined". I get it for every series in the website

### ISSUE THREAD

**Issue by ashtonmths** [BuXXe/movian-bs-plugin#7]
![657389b](https://user-images.githubusercontent.com/68967455/88838495-413f0d80-d1f7-11ea-9718-aa5d706ea276.jpg)

**Comment by BuXXe** [comment]
It has been a while since bs.to changed their api access and introduced the captcha system which made it problematic for many platforms like Kodi and movian to access their content. As long as they dont change this, I cannot repair the problems with the plugin.
